# In the following config file, please fill the fields as you need them.
# Do not use quotes, just plain text: e.g.:
# sql:
 # dbtype: sqlite
# etc.

# ================== Database Information =====================
sql:
    dbtype:   # either "sqlite" or "mysql"
    host:     # if dbtype = mysql, provide host
    user:     # if dbtype = mysql, provide user
    passwd:   # if dbtype = mysql, provide password
    dbname:   # provide a name for the database.


# ================== Twitter User Details =====================
# If you wish to save certain twitter user details, please just add the SQL data
# type you wish to save it as in the SQL database (recommended types are indicated
# in parantheses). If you do not wish to save a certain detail, just leave it empty
# like so:
# twitter_user_details:
    # contributors_enabled: TINYINT(1)
    # created at:
# This will save the detail "contributors_enabled" as booelan / tinyint into the
# database but it will not save "created_at" at all.

# TODO: add descriptions for user_details

twitter_user_details:
    contributors_enabled:  # TINYINT(1)
    created_at:  # DATETIME #REALLY
    default_profile:  # TINYINT(1)
    default_profile_image:  # TINYINT(1)
    description:  # TEXT (contains a dict)
    entities_description_urls:  # TEXT
    entities_url_urls:  # TEXT (contains a dict)
    favourites_count:  # BIGINT(30)
    follow_request_sent:  # TINYINT(1)
    followers_count:  # BIGINT(30)
    following:  # TINYINT(1)
    friends_count:  # BIGINT(30)
    geo_enabled:  # TINYINT(1)
    has_extended_profile:  # TINYINT(1)
    id:  # BIGINT(30) PRIMARY KEY
    id_str:  # VARCHAR(30)
    is_translation_enabled:  # TINYINT(1)
    is_translator:  # TINYINT(1)
    lang:  # VARCHAR(10)
    listed_count:  # BIGINT(30)
    location:  # TEXT
    name:  # VARCHAR (50)
    needs_phone_verification:  #TINYINT(1)
    notifications:  # TINYINT(1)
    profile_background_color:  # CHAR(6) (is a Hex Color Code)
    profile_background_image_url:  # TEXT
    profile_background_image_url_https:  # TEXT
    profile_background_tile:  # TINYINT(1)
    profile_banner_url:  # TEXT
    profile_image_url:  # TEXT
    profile_image_url_https:  # TEXT
    profile_link_color:  # CHAR(6) (is a Hex Color Code)
    profile_sidebar_border_color:  # CHAR(6) (is a Hex Color Code)
    profile_sidebar_fill_color:  # CHAR(6) (is a Hex Color Code)
    profile_text_color:  # CHAR(6) (is a Hex Color Code)
    profile_use_background_image:  # TINYINT(1)
    protected:  # TINYINT(1)
    screen_name:  # VARCHAR(50)
    status_contributors:  # TEXT (Rarely available)
    status_coordinates:  # TEXT (contains a dict)
    status_coordinates_coordinates:  # TEXT (Rarely available)
    status_coordinates_type:  # TEXT (Rarely available)
    status_created_at:  # DATETIME
    status_entities_hashtags:  # TEXT (contains a dict)
    status_entities_media:  # TEXT (contains a dict)
    status_entities_symbols:  # TEXT (contains a dict) # DE FACTO ALWAYS EMPTY
    status_entities_urls:  # TEXT (contains a dict)
    status_entities_user_mentions:  # TEXT (contains a dict)
    status_extended_entities_media:  # TEXT (contains a dict)
    status_favorite_count:  # INT(20)
    status_favorited:  # TINYINT(1)
    status_geo:  # TEXT (contains a dict)
    status_geo_coordinates:  # TEXT (Rarely available)
    status_geo_type:  # TEXT (Rarely available)
    status_id:  # BIGINT(50)
    status_id_str: # VARCHAR(50)
    status_in_reply_to_screen_name:  # VARCHAR(50)
    status_in_reply_to_status_id:  # BIGINT(50)
    status_in_reply_to_status_id_str:  # VARCHAR(50)
    status_in_reply_to_user_id:  # BIGINT(30)
    status_in_reply_to_user_id_str:  # VARCHAR(30)
    status_is_quote_status:  # TINYINT(1)
    status_lang:  # VARCHAR(10)
    status_place:  # TEXT (contains a dict)
    status_place_bounding_box_coordinates: # TEXT (Rarely available)
    status_place_bounding_box_type:  # TEXT (Rarely available)
    status_place_contained_within:  # TEXT (Rarely available)
    status_place_country:  # TEXT (Rarely available)
    status_place_country_code:  # TEXT (Rarely available)
    status_place_full_name:  # TEXT (Rarely available)
    status_place_id:  # TEXT (Rarely available)
    status_place_name: # TEXT (Rarely available)
    status_place_place_type:  # TEXT (Rarely available)
    status_place_url:  # TEXT (Rarely available)
    status_possibly_sensitive:  # TINYINT(1)
    status_quoted_status_id:  # BIGINT(50)
    status_quoted_status_id_str:  # VARCHAR(50)
    status_retweet_count:  # INT(30)
    status_retweeted:  # TINYINT(1)
    status_retweeted_status_contributors:  # TEXT (Rarely available)
    status_retweeted_status_coordinates:  # TEXT (contains a dict)
    status_retweeted_status_created_at:  # DATETIME
    status_retweeted_status_entities_hashtags:  # TEXT (contains a dict)
    status_retweeted_status_entities_media:  # TEXT (contains a dict)
    status_retweeted_status_entities_symbols:  # TEXT (Rarely available)
    status_retweeted_status_entities_urls:  # TEXT (contains a dict)
    status_retweeted_status_entities_user_mentions:  # TEXT (contains a dict)
    status_retweeted_status_extended_entities_media: # TEXT (contains a dict)
    status_retweeted_status_favorite_count:  # INT(30)
    status_retweeted_status_favorited:  # TINYINT(1)
    status_retweeted_status_geo:  # TEXT (contains a dict)
    status_retweeted_status_id:  # BIGINT(50)
    status_retweeted_status_id_str:  # VARCHAR(50)
    status_retweeted_status_in_reply_to_screen_name:  # VARCHAR(30)
    status_retweeted_status_in_reply_to_status_id:  # BIGINT(50)
    status_retweeted_status_in_reply_to_status_id_str:  # VARCHAR(50)
    status_retweeted_status_in_reply_to_user_id:  # BIGINT(30)
    status_retweeted_status_in_reply_to_user_id_str:  # VARCHAR(30)
    status_retweeted_status_is_quote_status:  # TINYINT(1)
    status_retweeted_status_lang:  # VARCHAR(10)
    status_retweeted_status_place:  # TEXT (contains a dict)
    status_retweeted_status_possibly_sensitive:  # TINYINT(1)
    status_retweeted_status_quoted_status_id:  # BIGINT(50)
    status_retweeted_status_quoted_status_id_str:  # VARCHAR(50)
    status_retweeted_status_retweet_count:  # INT(30)
    status_retweeted_status_retweeted:  # TINYINT(1)
    status_retweeted_status_source:  # TEXT
    status_retweeted_status_text:  # TEXT
    status_retweeted_status_truncated:  # TINYINT(1)
    status_source:  # TEXT
    status_text:  # TEXT
    status_truncated:  # TINYINT(1)
    statuses_count:  # BIGINT(30)
    suspended:  # TINYINT(1)
    time_zone: # TEXT (Rarely available)
    translator_type:  # VARCHAR(50)
    url:  # TEXT
    verified:  # BOOLEAN
    utc_offset:  # TEXT (Rarely available)


# ================== Notification Emails =====================


email_to_notify: 'user@example.com'

# mailgun details
# (find them under the respective domain name here: https://mailgun.com/app/domains)
mailgun_default_smtp_login: ''
mailgun_api_base_url: ''
mailgun_api_key: ''
