# In the following, please fill the fields as you need them.
# Do not use quotes, just plain text, e.g.:
# sql:
 # dbtype: sqlite
# etc.

sql:
    dbtype:   # only supports 'sqlite' at the moment
    host:     # TBI, please leave empty
    user:     # TBI, please leave empty
    passwd:   # TBI, please leave empty
    dbname:   # provide a name for the database
