# In the following, please fill the fields as you need them.
# Do not use quotes, just plain text: e.g.:
# sql:
 # dbtype: sqlite
# etc.

sql:
    dbtype:   # either "sqlite" or "mysql"
    host:     # if dbtype = mysql, provide host
    user:     # if dbtype = mysql, provide user
    passwd:   # if dbtype = mysql, provide password
    dbname:   # provide a name for the database.

# If you wish to save certain twitter user details, please indicate the SQL data
# type you wish to save it as in the SQL database. If you do not wish to save
# a certain detail, just leave it empty like so:
# twitter_user_details:
    # contributors_enabled: TINYINT
    # created at:
# This will save the detail "contributors_enabled" as booelan / tinyint into the
# database but it will not save "created_at" at all.

# TODO: add descriptions for user_details

twitter_user_details:
    contributors_enabled:
    created_at:
    default_profile:
    default_profile_image:
    description:
    entities_description_urls:
    entities_url_urls:
    favourites_count:
    follow_request_sent:
    followers_count:
    following:
    friends_count:
    geo_enabled:
    has_extended_profile:
    id:
    id_str:
    is_translation_enabled:
    is_translator:
    lang:
    listed_count:
    location:
    name:
    needs_phone_verification:
    notifications:
    profile_background_color:
    profile_background_image_url:
    profile_background_image_url_https:
    profile_background_tile:
    profile_banner_url:
    profile_image_url:
    profile_image_url_https:
    profile_link_color:
    profile_sidebar_border_color:
    profile_sidebar_fill_color:
    profile_text_color:
    profile_use_background_image:
    protected:
    screen_name:
    status_contributors:
    status_coordinates:
    status_coordinates_coordinates:
    status_coordinates_type:
    status_created_at:
    status_entities_hashtags:
    status_entities_media:
    status_entities_symbols:
    status_entities_urls:
    status_entities_user_mentions:
    status_extended_entities_media:
    status_favorite_count:
    status_favorited:
    status_geo:
    status_geo_coordinates:
    status_geo_type:
    status_id:
    status_id_str:
    status_in_reply_to_screen_name:
    status_in_reply_to_status_id:
    status_in_reply_to_status_id_str:
    status_in_reply_to_user_id:
    status_in_reply_to_user_id_str:
    status_is_quote_status:
    status_lang:
    status_place:
    status_place_bounding_box_coordinates:
    status_place_bounding_box_type:
    status_place_contained_within:
    status_place_country:
    status_place_country_code:
    status_place_full_name:
    status_place_id:
    status_place_name:
    status_place_place_type:
    status_place_url:
    status_possibly_sensitive:
    status_quoted_status_id:
    status_quoted_status_id_str:
    status_retweet_count:
    status_retweeted:
    status_retweeted_status_contributors:
    status_retweeted_status_coordinates:
    status_retweeted_status_created_at:
    status_retweeted_status_entities_hashtags:
    status_retweeted_status_entities_media:
    status_retweeted_status_entities_symbols:
    status_retweeted_status_entities_urls:
    status_retweeted_status_entities_user_mentions:
    status_retweeted_status_extended_entities_media:
    status_retweeted_status_favorite_count:
    status_retweeted_status_favorited:
    status_retweeted_status_geo:
    status_retweeted_status_id:
    status_retweeted_status_id_str:
    status_retweeted_status_in_reply_to_screen_name:
    status_retweeted_status_in_reply_to_status_id:
    status_retweeted_status_in_reply_to_status_id_str:
    status_retweeted_status_in_reply_to_user_id:
    status_retweeted_status_in_reply_to_user_id_str:
    status_retweeted_status_is_quote_status:
    status_retweeted_status_lang:
    status_retweeted_status_place:
    status_retweeted_status_possibly_sensitive:
    status_retweeted_status_quoted_status_id:
    status_retweeted_status_quoted_status_id_str:
    status_retweeted_status_retweet_count:
    status_retweeted_status_retweeted:
    status_retweeted_status_source:
    status_retweeted_status_text:
    status_retweeted_status_truncated:
    status_source:
    status_text:
    status_truncated:
    statuses_count:
    suspended:
    time_zone:
    translator_type:
    url:
    verified:
    utc_offset:
