# In the following, please fill the fields as you need them.
# Do not use quotes, just plain text: e.g.:
# sql:
 # dbtype: sqlite
# etc.

sql:
    dbtype: sqlite   # either "sqlite" or "mysql"
    host:     # if dbtype = mysql, provide host
    user:     # if dbtype = mysql, provide user
    passwd:   # if dbtype = mysql, provide password
    dbname: test_db   # provide a name for the database.

# If you wish to save certain twitter user details, please indicate the SQL data
# type you wish to save it as in the SQL database. If you do not wish to save
# a certain detail, just leave it empty like so:
# twitter_user_details:
    # contributors_enabled: TINYINT
    # created at:
# This will save the detail "contributors_enabled" as booelan / tinyint into the
# database but it will not save "created_at" at all.

# TODO: add descriptions for user_details

twitter_user_details:
    contributors_enabled:
    created_at:
    default_profile:
    default_profile_image:
    description:
    entities.description.urls:
    entities.url.urls:
    favourites_count:
    follow_request_sent:
    followers_count: INT
    following:
    friends_count:
    geo_enabled:
    has_extended_profile:
    id: INT PRIMARY KEY
    id_str:
    is_translation_enabled:
    is_translator:
    lang: CHAR
    listed_count:
    location:
    name:
    needs_phone_verification:
    notifications:
    profile_background_color:
    profile_background_image_url:
    profile_background_image_url_https:
    profile_background_tile:
    profile_banner_url:
    profile_image_url:
    profile_image_url_https:
    profile_link_color:
    profile_sidebar_border_color:
    profile_sidebar_fill_color:
    profile_text_color:
    profile_use_background_image:
    protected:
    screen_name:
    status.contributors:
    status.coordinates:
    status.coordinates.coordinates:
    status.coordinates.type:
    status.created_at:
    status.entities.hashtags:
    status.entities.media:
    status.entities.symbols:
    status.entities.urls:
    status.entities.user_mentions:
    status.extended_entities.media:
    status.favorite_count:
    status.favorited:
    status.geo:
    status.geo.coordinates:
    status.geo.type:
    status.id:
    status.id_str:
    status.in_reply_to_screen_name:
    status.in_reply_to_status_id:
    status.in_reply_to_status_id_str:
    status.in_reply_to_user_id:
    status.in_reply_to_user_id_str:
    status.is_quote_status:
    status.lang:
    status.place:
    status.place.bounding_box.coordinates:
    status.place.bounding_box.type:
    status.place.contained_within:
    status.place.country:
    status.place.country_code:
    status.place.full_name:
    status.place.id:
    status.place.name:
    status.place.place_type:
    status.place.url:
    status.possibly_sensitive:
    status.quoted_status_id:
    status.quoted_status_id_str:
    status.retweet_count:
    status.retweeted:
    status.retweeted_status.contributors:
    status.retweeted_status.coordinates:
    status.retweeted_status.created_at:
    status.retweeted_status.entities.hashtags:
    status.retweeted_status.entities.media:
    status.retweeted_status.entities.symbols:
    status.retweeted_status.entities.urls:
    status.retweeted_status.entities.user_mentions:
    status.retweeted_status.extended_entities.media:
    status.retweeted_status.favorite_count:
    status.retweeted_status.favorited:
    status.retweeted_status.geo:
    status.retweeted_status.id:
    status.retweeted_status.id_str:
    status.retweeted_status.in_reply_to_screen_name:
    status.retweeted_status.in_reply_to_status_id:
    status.retweeted_status.in_reply_to_status_id_str:
    status.retweeted_status.in_reply_to_user_id:
    status.retweeted_status.in_reply_to_user_id_str:
    status.retweeted_status.is_quote_status:
    status.retweeted_status.lang:
    status.retweeted_status.place:
    status.retweeted_status.possibly_sensitive:
    status.retweeted_status.quoted_status_id:
    status.retweeted_status.quoted_status_id_str:
    status.retweeted_status.retweet_count:
    status.retweeted_status.retweeted:
    status.retweeted_status.source:
    status.retweeted_status.text:
    status.retweeted_status.truncated:
    status.source:
    status.text:
    status.truncated:
    statuses_count:
    suspended:
    time_zone: CHAR
    translator_type:
    url:
    verified:
    utc_offset:
