# In the following, please fill the fields as you need them.
# Do not use quotes, just plain text, e.g.:
# mysql:
 # dbtype: sqlite
# etc.

mysql:
    dbtype: sqlite   # only supports 'sqlite' at the moment
    host:     # TBI, please leave empty
    user:     # TBI, please leave empty
    passwd:   # TBI, please leave empty
    dbname: test_db   # provide a name for the database
